### ISSUE TITLE
Might be that verisure has closed down this api now. The solution would be to start using version-2 of python-verisure. This is homeassistant, right?

### ISSUE THREAD

**Issue by maol01** [persandstrom/python-verisure#161]
Might be that verisure has closed down this api now. The solution would be to start using version-2 of python-verisure. This is homeassistant, right?

_Originally posted by @persandstrom in https://github.com/persandstrom/python-verisure/issues/160#issuecomment-1470343923_

I updated/started using Version 2 python-verisure but now I lost the ability to get images from my Verisure Cams, Any idees how to solve that? This is a screen dump from the log
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/verisure/coordinator.py:157
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 14:46:56 (16 occurrences)
Last logged: 15:47:46

[140654816165312] 'NoneType' object has no attribute 'get'
[140654753822080] 'NoneType' object has no attribute 'get'
[140654818527456] 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1808, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1845, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 795, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 686, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 961, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 726, in _handle_entity_call
    await result
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/verisure/camera.py", line 139, in capture_smartcam
    self.coordinator.smartcam_capture(self.serial_number)
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 190, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/verisure/coordinator.py", line 157, in smartcam_capture
    .get("requestId")
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by persandstrom** [comment]
Hi, you need to wait for the home-assistant integration component to be updated, I will close this Issue since I think you didn't want to create a new Issue but comment in the other tread
