### ISSUE TITLE
Vacationmode reports error

### ISSUE THREAD

**Issue by TheLion** [persandstrom/python-verisure#79]
Hi.

When running `python verisure.py username password vacationmode` an error is reported.

```
Traceback (most recent call last):
  File "verisure.py", line 3, in <module>
    __main__.main()
  File "/home/pi/domoticz/www/python-app_api/verisure/__main__.py", line 245, in main
    print_result(session.get_vacation_mode())
  File "/home/pi/domoticz/www/python-app_api/verisure/session.py", line 424, in get_vacation_mode
    urls.get_vacationmode(self._giid),
TypeError: get_vacationmode() takes no arguments (1 given)
```

**Comment by persandstrom** [comment]
Thanks!
It's solved in the latest version
