### ISSUE TITLE
Invalid session cookie

### ISSUE THREAD

**Issue by Redferne** [persandstrom/python-verisure#96]
Getting a lot of these lately in Home Assistant log. They repeat every 30 seconds. Not sure that there is anything that can be done except handling the 401 response a bit nicer?

```
2018-02-12 09:04:08 ERROR (SyncWorker_1) [homeassistant.components.verisure] Could not read overview, Invalid respons
e, status code: 401 - Data: {"errorGroup":"UNAUTHORIZED","errorCode":"AUT_00011","errorMessage":"Invalid session cook
ie"} 
2018-02-12 09:04:08 ERROR (MainThread) [homeassistant.helpers.entity] Update for lock.framdorr fails 
Traceback (most recent call last): 
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 201, in async_update_ha
_state 
    yield from self.async_device_update() 
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 308, in async_device_up
date 
    yield from self.hass.async_add_job(self.update) 
  File "/usr/local/lib/python3.6/asyncio/futures.py", line 332, in __iter__ 
    yield self  # This tells Task to wait for completion. 
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup 
    future.result() 
  File "/usr/local/lib/python3.6/asyncio/futures.py", line 245, in result 
    raise self._exception 
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run 
    result = self.fn(*self.args, **self.kwargs) 
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/lock/verisure.py", line 76, in update
 
    hub.update_overview() 
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/util/__init__.py", line 306, in wrapper 
    result = method(*args, **kwargs) 
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/components/verisure.py", line 147, in update_ove
rview 
    self.overview = self.session.get_overview() 
  File "/srv/homeassistant/lib/python3.6/site-packages/verisure/session.py", line 130, in get_overview 
    _validate_response(response) 
  File "/srv/homeassistant/lib/python3.6/site-packages/verisure/session.py", line 15, in _validate_response 
    raise ResponseError(response.status_code, response.text) 
verisure.session.ResponseError: Invalid response, status code: 401 - Data: {"errorGroup":"UNAUTHORIZED","errorCode":"
AUT_00011","errorMessage":"Invalid session cookie"} 
```

**Comment by januskh** [comment]
I believe that Verisure have changed their endpoints. I'm getting these too, on another project.

**Comment by januskh** [comment]
I just recieved the same error. But that was because I had changed my password for my account, and forgotten to change it in my code.

**Comment by kimhaak** [comment]
Seeing this too, only after a period of time,30-45 minutes, then service needs to be restarted. (Using a mqtt service that utilizes this project)

DEBUG:urllib3.connectionpool:https://e-api01.verisure.com:443 "GET /xbn/2/installation/46490583256/overview HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): e-api01.verisure.com:443
DEBUG:urllib3.connectionpool:https://e-api01.verisure.com:443 "PUT /xbn/2/installation/46490583256/device/2AGN%20QUKY/lock HTTP/1.1" 401 None
INFO:root:Invalid response, status code: 401 - Data: {"errorGroup":"UNAUTHORIZED","errorCode":"AUT_00011","errorMessage":"Invalid session cookie"}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): e-api01.verisure.com:443
